name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run linting
        id: lint
        run: npm run lint
    outputs:
      lint-status: ${{ steps.lint.outcome }}

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        id: test
        run: npm run test
    outputs:
      test-status: ${{ steps.test.outcome }}

  block_merge:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Check if any job failed
        run: |
          if [[ "${{ needs.lint.outputs.lint-status }}" != "success" || "${{ needs.test.outputs.test-status }}" != "success" ]]; then
            echo "PR cannot be merged due to failed checks";
            exit 1;
          fi
